name: 'google-chat-notification'
description: 'Google Chat Notification for GitHub Actions'
author: 'thenationofalex'
inputs:
  name:
    description: 'job name.'
    required: true
  url:
    description: 'google chat webhook url.'
    required: true
  status:
    description: 'job status.'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'green'